Traceback (most recent call last):
  File "train_model_on_different_locations.py", line 157, in <module>
    cfg.EXPERIMENT_PATH.mkdir(parents=True, exist_ok=False)
  File "/home/anatbr/students/noamshakedc/env/anaconda3/envs/ml2/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: 'exps/CNN_mmd2_1e-6'
